# Generated by Django 5.2.7 on 2025-10-17 07:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('hashed_key', models.CharField(editable=False, max_length=255)),
                ('owner', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked', models.BooleanField(default=False)),
                ('quota_requests_per_minute', models.IntegerField(default=60)),
                ('quota_requests_per_day', models.IntegerField(default=1000)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'api_keys',
                'indexes': [models.Index(fields=['hashed_key'], name='api_keys_hashed__711aef_idx'), models.Index(fields=['revoked'], name='api_keys_revoked_6db9fe_idx')],
            },
        ),
        migrations.CreateModel(
            name='IDValidationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endpoint', models.CharField(max_length=200)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.IntegerField()),
                ('response_time', models.FloatField(help_text='Response time in milliseconds')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('request_data', models.JSONField(blank=True, default=dict)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='validator.apikey')),
            ],
            options={
                'db_table': 'id_validation_log',
                'indexes': [models.Index(fields=['api_key', 'created_at'], name='id_validati_api_key_1df686_idx'), models.Index(fields=['created_at'], name='id_validati_created_b79508_idx'), models.Index(fields=['endpoint'], name='id_validati_endpoin_a924d2_idx'), models.Index(fields=['status_code'], name='id_validati_status__6f62da_idx')],
            },
        ),
    ]
