# Generated by Django 5.2.7 on 2025-10-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0002_remove_apikey_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='prefix_key',
            field=models.CharField(default='H774ucDc', editable=False, max_length=255),
            preserve_default=False,
        ),
    ]
