# Generated by Django 5.2.7 on 2025-10-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0003_apikey_prefix_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='quota_requests_per_day',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='quota_requests_per_minute',
            field=models.IntegerField(default=10),
        ),
    ]
